OpenWRT 22.03.0 with updated PLC setup script

diff --git a/patches/0004-plc-script.patch b/patches/0004-plc-script.patch
--- a/patches/0004-plc-script.patch
+++ b/patches/0004-plc-script.patch
@@ -2,7 +2,7 @@ diff --git a/target/linux/ath79/generic/base-files/etc/init.d/plc b/target/linux
 new file mode 100755
 --- /dev/null
 +++ b/target/linux/ath79/generic/base-files/etc/init.d/plc
-@@ -0,0 +1,295 @@
+@@ -0,0 +1,329 @@
 +#!/bin/sh /etc/rc.common
 +
 +USE_PROCD=1
@@ -221,41 +221,75 @@ new file mode 100755
 +}
 +
 +setup() {
-+	error=0
-+	if [ -z "$(which unsquashfs)" ]; then
-+		echo "unsquashfs missing. Install squashfs-tools-unsquashfs package" >&2
-+		error=1
++	echo -n "Download original firmware and extract files from /lib/plc to /etc/plc [y|n] "
++	read i
++	if [ "$i" = "y" ] || [ "$i" = "Y" ]; then
++		if [ -z "$(which unsquashfs)" ]; then
++			echo "unsquashfs missing. Install squashfs-tools-unsquashfs package" >&2
++			exit 1
++		fi
++
++		cd /tmp
++		FW="COVRP2500A1_FW101b08_decrypted.bin"
++		rm -f "$FW"
++		wget -O "$FW" "http://pmdap.dlink.com.tw/PMD/GetAgileFile?itemNumber=FIR1800225&fileName=COVRP2500A1_FW101b08_decrypted.bin&fileSize=1.5990457E7;1.5992229E7;65141.0;"
++		if [ ! -f "$FW" ]; then
++			echo "Download failed. Check network" >&2
++			exit 1
++		fi
++		unsquashfs -lls "$FW" /lib/plc | grep -q '\.pib$'
++		if [ $? -ne 0 ]; then
++			echo "$FW does not contain any /lib/plc/*.pib files" >&2
++			exit 1
++		fi
++
++		unsquashfs "$FW" /lib/plc
++		mkdir -p /etc/plc/
++		cp squashfs-root/lib/plc/* /etc/plc/
++		rm -rf squashfs-root
++		rm "$FW"
 +	fi
-+	if [ $error -eq 1 ]; then
++
++	options=$(echo /etc/plc/*.pib)
++	if [ "$options" = "/etc/plc/*.pib" ]; then
++		echo "No files matching /etc/plc/*.pib" >&2
 +		exit 1
 +	fi
-+
-+	cd /tmp
-+	FW="COVRP2500A1_FW101b08_decrypted.bin"
-+	wget -O "$FW" "http://pmdap.dlink.com.tw/PMD/GetAgileFile?itemNumber=FIR1800225&fileName=COVRP2500A1_FW101b08_decrypted.bin&fileSize=1.5990457E7;1.5992229E7;65141.0;"
-+
-+	unsquashfs "$FW" /lib/plc
-+	mkdir -p /etc/plc/
-+	cp squashfs-root/lib/plc/* /etc/plc/
-+	rm -rf squashfs-root
-+	rm "$FW"
-+
-+	options=/etc/plc/COVRP2500*.pib
 +	count=$(echo $options | wc -w)
 +	i=""
 +	while [ -z "$i" ] || [ $i -lt 1 ] || [ $i -gt $count ]; do
 +		i=1
-+		for f in /etc/plc/COVRP2500*.pib; do
++		for f in $options; do
 +			echo "${i}) $f"
 +			i=$((i+1))
 +		done
 +		echo -n "Select PibPath [1-${count}]: "
 +		read i
 +	done
-+	pibpath=$(echo /etc/plc/COVRP2500*.pib | awk '{print$'$i'}')
++	pibpath=$(echo $options | awk '{print$'$i'}')
 +	uci set plc.config.PibPath=$pibpath
 +
-+	nvmpath=$(echo /etc/plc/*.nvm)
++	options=$(echo /etc/plc/*.nvm)
++	if [ "$options" = "/etc/plc/*.nvm" ]; then
++		echo "No files matching /etc/plc/*.nvm" >&2
++		exit 1
++	fi
++	count=$(echo $options | wc -w)
++	if [ $count -gt 1 ]; then
++		i=""
++		while [ -z "$i" ] || [ $i -lt 1 ] || [ $i -gt $count ]; do
++			i=1
++			for f in $options; do
++				echo "${i}) $f"
++				i=$((i+1))
++			done
++			echo -n "Select NvmPath [1-${count}]: "
++			read i
++		done
++		nvmpath=$(echo $options | awk '{print$'$i'}')
++	else
++		nvmpath=$options
++	fi
 +	uci set plc.config.NvmPath=$nvmpath
 +
 +	echo -n "NetworkPasswd (leave empty to use default plc_networkpwd): "
